// Copyright (c) 2026 T. C. Raymond
// SPDX-License-Identifier: MIT
//
// Shared adaptive mesh refinement (AMR) helpers. These are physics-agnostic so
// the electrostatic solver (and, later, the magnetostatic / MQS solvers) can
// reuse the same marking and conforming-refinement policy.

#pragma once

#include <algorithm>
#include <stdexcept>
#include <vector>

#include "mfem.hpp"

namespace amr {

	// One AMR iteration's diagnostics, recorded during RunAdaptive(). Exposed for
	// tests (convergence / conformity assertions) and console logging.
	struct AmrIterationInfo {
		long   true_dofs;     // global true DOFs on that iteration's mesh
		double global_error;  // sqrt(sum_k eta_k^2), combined over scenarios
		double peak_field_magnitude;     // max |B| sampled over the mesh
	};

	// Total field energy of @p u under the operator generated by @p integrator,
	//     Et = 0.5 * u^T K u,
	// where K is the UNCONSTRAINED domain stiffness. Takes ownership of
	// @p integrator (the BilinearForm below deletes it).
	//
	// This is the normalization constant for the recovery-based error
	// indicators. The ZZ indicator eta_k has units of sqrt(energy), so eta_k
	// scales linearly with the excitation amplitude; dividing by sqrt(Et)
	// removes that scale and leaves a dimensionless RELATIVE error. Without it,
	// folding indicators across scenarios compares raw magnitudes, and the
	// scenario with the largest excitation wins the fold on scale alone rather
	// than on discretization error -- which is precisely the coupling-matrix
	// case, where one synthesized scenario exists per terminal.
	//
	// Uses the same integrator factory as the solve and the estimator, so the
	// energy measure carries the same geometry weight (axisymmetric 2*pi*r) and
	// the same material coefficient.
	inline double FieldEnergy(mfem::FiniteElementSpace& fes,
							  mfem::BilinearFormIntegrator* integrator,
							  const mfem::GridFunction& u) {
		mfem::BilinearForm k(&fes);
		k.AddDomainIntegrator(integrator); // k takes ownership
		k.Assemble();
		k.Finalize();
		// Energy is a nonnegative quadratic form, but roundoff on a nearly-null
		// solution can produce a small negative value; clamp so callers can take
		// a square root unconditionally.
		return std::max(0.0, 0.5 * k.InnerProduct(u, u));
	}

	// Bulk (Dorfler) marking. Selects the smallest set of elements whose summed
	// SQUARED error reaches @p fraction of the total squared error.
	//
	//   total = sum_k errors[k]^2
	//   mark elements (largest error first) until accumulated squared error
	//   reaches fraction * total.
	//
	// @p errors   Per-element error indicators (NOT squared); errors[k] >= 0.
	// @p fraction Marking fraction in (0, 1]; values outside are clamped.
	// @p marked   Output: indices of elements to refine (cleared first).
	inline void MarkElementsDorfler(const mfem::Vector& errors, double fraction,
									mfem::Array<int>& marked) {
		marked.SetSize(0);
		const int ne = errors.Size();
		if (ne == 0) { return; }

		// Clamp the fraction into (0, 1]; fall back to the spec default on garbage.
		if (!(fraction > 0.0)) { fraction = 0.7; }
		if (fraction > 1.0)    { fraction = 1.0; }

		// Total "energy" = sum of squared errors.
		double total = 0.0;
		for (int i = 0; i < ne; ++i) { total += errors(i) * errors(i); }
		if (!(total > 0.0)) { return; } // No estimated error -> nothing to refine.

		// Sort element indices by descending error.
		std::vector<int> idx(static_cast<std::size_t>(ne));
		for (int i = 0; i < ne; ++i) { idx[static_cast<std::size_t>(i)] = i; }
		std::sort(idx.begin(), idx.end(),
				  [&errors](int a, int b) { return errors(a) > errors(b); });

		const double threshold = fraction * total;
		double accum = 0.0;
		for (int i = 0; i < ne; ++i) {
			const int e = idx[static_cast<std::size_t>(i)];
			accum += errors(e) * errors(e);
			marked.Append(e);
			if (accum >= threshold) { break; }
		}
	}

	// Conforming refinement of @p marked elements. For simplex (triangular) meshes
	// MFEM performs bisection (red/green) refinement that resolves without hanging
	// nodes. Passing nonconforming = 0 forces the conforming path.
	//
	// The downstream C# results pipeline (TriangleLocator / FemFieldSampler /
	// ResultsView) assumes a conforming triangle tiling, so a non-conforming result
	// is treated as an error rather than silently exported.
	inline void RefineConforming(mfem::Mesh& mesh, const mfem::Array<int>& marked) {
		if (marked.Size() == 0) { return; }

		mesh.GeneralRefinement(marked, /*nonconforming=*/0);

		// Hard requirement: the exported mesh must be free of hanging nodes. If MFEM
		// could not satisfy the request conformingly it falls back to a
		// non-conforming representation; reject that here.
		if (mesh.Nonconforming()) {
			throw std::runtime_error(
				"AMR: conforming refinement was requested but the mesh became "
				"non-conforming (hanging nodes). Conforming AMR is only supported "
				"for simplex (triangular) meshes. Re-mesh with triangles or "
				"disable AMR.");
		}
	}

} // namespace amr
